feat(i18n): update zh-CN texts
wokwi/wokwi-docs pull request #123
Opened 2022-07-16 13:19 UTC by breakeryu

update libraries and serial-moitor texts.

2022-07-18 23:27 UTC, breakeryu commented
@Does anyone is here?

2022-07-20 14:45 UTC, urish requested changes
Thanks for the translation!

I see that the source files you translated are a bit old, they have been updated in the English version since they were copies from there.

Do you need help with finding the changes?

Also, I left two comments on the translation itself.

2022-07-20 14:45 UTC, urish commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/libraries.md
>  # Sample libraries.txt file:
Can you please translate this title too?

2022-07-20 14:45 UTC, urish commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/libraries.md
> +You can find the library names in the Arduino Library Manager. Alternatively, you can find it inside the source code of the library. Look for the `name` field of the `library.properties` file.（这句话不太懂
You wrote some question in Chinese, I guess it is not part of the translation. How can I help?

2022-07-21 02:48 UTC, breakeryu commented
thankyou，urish。I will check again。

2022-07-21 05:20 UTC, breakeryu commented
hi,urish. How can I solve this requested changes probelm? 
I have checked my docs and added a new pull requeset.

2022-07-22 00:55 UTC, closed without merging