feat(wokwi-hx711): add docs for HX711 Load Cell Amplifier
wokwi/wokwi-docs pull request #142
Opened 2022-10-01 01:57 UTC by ishotjr

2022-10-01 12:00 UTC, urish requested changes
Thanks! I added some comments, also - please add this to sidebar.js (this is the file that controls the documentation ToC)

2022-10-01 12:00 UTC, urish commented on docs/parts/wokwi-hx711.md
> +The HX711 amplifier allows you to easily read load cells and evaluate changes in resistance. A Wheatstone bridge is used to connect load cells to the IC, which is in turn connected to the microcontro
It's worth mentioning that all these methods are part of the `HX711` library for Arduino (I can see there are several Arduino libraries for interfacing with the HX711).

2022-10-01 12:00 UTC, urish commented on docs/parts/wokwi-hx711.md
> +<wokwi-hx711 type="5kg" />
We usually create a table at the bottom of the "Attributes" section with examples of how the attributes affect the visual style of the element, e.g. [here](https://docs.wokwi.com/parts/wokwi-7segment#examples)

2022-10-05 20:24 UTC, urish commented
Thanks! A few more things:

1. There's a typo: guage -> gauge (note that the 3rd example in the "Examples" table is the same as the 2nd example, because of the typo).
2. Can we simplify the example in the docs? Ideally, the example would be just the minimal thing the user need to get some input from the sensor, and then we can have links to more elaborate examples in the "Simulator examples" section.
3. Can you please format the markdown file with prettier, to keep consistent with the other files? There's a prettier extension for VSCode, but you can also type `npx prettier --write docs` in the terminal to reformat everything (just don't commit unrelated files)

2022-10-10 13:00 UTC, ishotjr commented
@urish that's so strange RE `guage` - I pasted the whole thing into Word to check for typos before submitting the PR! 😅 Requested changes are in, please let me know if there's anything else! :bowtie:

2022-10-10 13:02 UTC, merged